# Generated by Django 5.1.3 on 2025-01-15 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='total_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
