# Generated by Django 5.1.3 on 2025-01-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_quizresult_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='how_many_questions',
            field=models.IntegerField(default=0),
        ),
    ]
